#------------------------------------------------------------------------------
# en: GENERAL CONFIGURATION | ru: ОБЩАЯ КОНФИГУРАЦИЯ
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# en: Threading Configuration | ru: Конфигурация потоков
#------------------------------------------------------------------------------
# en: Controls parallel execution capacity (min: 1) | ru: Управление количеством параллельных выполнений (минимум: 1)
threads: 1

#------------------------------------------------------------------------------
# en: Timing Settings | ru: Настройки времени
#------------------------------------------------------------------------------
# en: Initial delay range before starting operations (seconds) | ru: Диапазон начальной задержки перед началом выполнения (секунды)
delay_before_start:
    min: 10
    max: 15

# en: Delay between tasks (seconds) | ru: Задержка между задачами (секунды)
delay_between_tasks:
    min: 100
    max: 150

#------------------------------------------------------------------------------
# en: NETWORK CONFIGURATION | ru: КОНФИГУРАЦИЯ СЕТИ
#------------------------------------------------------------------------------
# en: Somnia Testnet RPC endpoint | ru: RPC-эндпоинт тестовой сети Somnia
somnia_rpc: https://dream-rpc.somnia.network

# en: Somnia Testnet Explorer | ru: Эксплорер тестовой сети Somnia
somnia_explorer: https://shannon-explorer.somnia.network/

#------------------------------------------------------------------------------
# en: TELEGRAM CONFIGURATION | ru: КОНФИГУРАЦИЯ TELEGRAM
#------------------------------------------------------------------------------
# en: Telegram API hash and ID | ru: Telegram API hash и ID
# https://my.telegram.org/apps 
telegram_api_id: ""
telegram_api_hash: ""

# en: Telegram notifications | ru: Уведомления Telegram
send_stats_to_telegram: true

# en: Bot token and user ID | ru: Токен бота и ID пользователя
tg_token: ""  # https://t.me/BotFather
tg_id: ""  # https://t.me/getmyid_bot

#------------------------------------------------------------------------------
# en: TASK CONFIGURATION | ru: КОНФИГУРАЦИЯ ЗАДАЧ
#------------------------------------------------------------------------------
# en: Referral code for standard account registration | ru: Реферальный код для стандартной регистрации аккаунтов
referral_code: ""

# en: Tasks that will always run regardless of their status
# ru: Задачи, которые будут выполняться всегда, независимо от их статуса
always_run_tasks:
  # en: Module names to always run | ru: Имена модулей, задачи которых нужно выполнять всегда
  modules: ["faucet", "transfer_stt", "mint_message_nft", "onchain_gm", "daily_gm"]

# en: Available module names (copy needed modules to the list above)
# ru: Доступные имена модулей (скопируйте нужные модули в список выше)
available_modules:
  - "profile"           # Профиль
  - "faucet"            # Кран для получения токенов
  - "transfer_stt"      # Перевод STT
  - "mint_usdt"         # Минт USDT
  - "mint_ping_pong"    # Минт Ping/Pong
  - "swap_ping_pong"    # Обмен Ping/Pong
  - "mint_message_nft"  # Минт NFT сообщения
  - "mint_air"          # Минт контракта токена
  - "onchain_gm"        # Onchain GM
  - "shannon_nft"       # Shannon NFT
  - "yappers_nft"       # Yappers NFT
  - "mint_domen"        # Минт домена
  - "nerzo_nft"         # Nerzo NFT
  - "somni_nft"         # Минт Somni NFT
  - "daily_gm"          # Ежедневный GM
  - "quest_yapper"      # Somnia Yappers

#------------------------------------------------------------------------------
# en: TOKEN CONFIGURATION | ru: КОНФИГУРАЦИЯ ТОКЕНОВ
#------------------------------------------------------------------------------
# en: Define tokens and their percentage ranges to be used in operations 
# ru: Определение токенов и их процентных диапазонов для использования в операциях
tokens:
  # en: Token name/symbol | ru: Название/символ токена
  STT:
    # en: Percentage range of token amount to use | ru: Диапазон процентов от суммы токенов для использования
    percent_range:
      min: 5  # 5%
      max: 10 # 10%
    # en: Contract address | ru: Адрес контракта
    contract_address: "0x0000000000000000000000000000000000000000"
  WSTT:
    percent_range:
      min: 5
      max: 10
    # en: Contract address (ERC20) | ru: Адрес контракта (ERC20)
    contract_address: "0x4A3BC48C156384f9564Fd65A53a2f3D534D8f2b7"
  USDT:
    percent_range:
      min: 30
      max: 50
    # en: Contract address (ERC20) | ru: Адрес контракта (ERC20)
    contract_address: "0xE9CC37904875B459Fa5D0FE37680d36F1ED55e38"