#------------------------------------------------------------------------------
# en: Threading Configuration | ru: Конфигурация потоков
#------------------------------------------------------------------------------
# en: Controls parallel execution capacity (min: 1) | ru: Управление количеством параллельных выполнений (минимум: 1)
threads: 10


#------------------------------------------------------------------------------
# en: Timing Settings | ru: Настройки времени
#------------------------------------------------------------------------------
# en: Initial delay range before starting operations (seconds) | ru: Диапазон начальной задержки перед началом выполнения (секунды)
delay_before_start:
    min: 0
    max: 0

# en: Delay between tasks (seconds) | ru: Задержка между задачами (секунды)
delay_between_tasks:
    min: 30
    max: 120


#------------------------------------------------------------------------------
# en: Telegram API hash and ID | ru: Telegram API hash и ID
#------------------------------------------------------------------------------
# https://my.telegram.org/apps 

telegram_api_id: ""
telegram_api_hash: ""


#------------------------------------------------------------------------------
# en: MODULES CONFIGURATION  | ru: КОНФИГУРАЦИИ МОДУЛЕЙ
#------------------------------------------------------------------------------
# en: Referral code for standard account registration | ru: Реферальный код для стандартной регистрации аккаунтов
referral_code: ""


#------------------------------------------------------------------------------
# en: Task Execution Configuration | ru: Настройки выполнения задач
#------------------------------------------------------------------------------
# en: Tasks that will always run regardless of their status
# ru: Задачи, которые будут выполняться всегда, независимо от их статуса
always_run_tasks:
  # en: Module names to always run | ru: Имена модулей, задачи которых нужно выполнять всегда
  modules: ["faucet", "mint_message_nft"]  # пример: ["faucet", "profile"]

# en: Available module names (copy needed modules to the list above)
# ru: Доступные имена модулей (скопируйте нужные модули в список выше)
available_modules:
  - "profile"           # Профиль
  - "faucet"            # Кран для получения токенов
  - "transfer_stt"      # Перевод STT
  - "mint_ping_pong"    # Минт Ping/Pong
  - "swap_ping_pong"    # Обмен Ping/Pong
  - "mint_usdt"         # Минт USDT
  - "mint_message_nft"  # Минт NFT сообщения
  - "deploy_token_contract"  # Деплой контракта токена
  - "quest_socials"     # Квест по социальным сетям
  - "quest_sharing"     # Квест по шерингу


#------------------------------------------------------------------------------
# Network Settings
#------------------------------------------------------------------------------
# Somnia Testnet RPC endpoint
somnia_rpc: https://dream-rpc.somnia.network

# Somnia Testnet Explorer
somnia_explorer: https://shannon-explorer.somnia.network/


#------------------------------------------------------------------------------
# en: Tokens Configuration | ru: Конфигурация токенов
#------------------------------------------------------------------------------
# en: Define tokens and their percentage ranges to be used in operations 
# ru: Определение токенов и их процентных диапазонов для использования в операциях
tokens:
  # en: Token name/symbol | ru: Название/символ токена
  STT:
    # en: Percentage range of token amount to use | ru: Диапазон процентов от суммы токенов для использования
    percent_range:
      min: 5  # 5%
      max: 10 # 10%
    # en: Contract address | ru: Адрес контракта
    contract_address: "0x0000000000000000000000000000000000000000"
  WSTT:
    percent_range:
      min: 5
      max: 10
    # en: Contract address (ERC20) | ru: Адрес контракта (ERC20)
    contract_address: "0x4A3BC48C156384f9564Fd65A53a2f3D534D8f2b7"
  USDT:
    percent_range:
      min: 30
      max: 50
    # en: Contract address (ERC20) | ru: Адрес контракта (ERC20)
    contract_address: "0xE9CC37904875B459Fa5D0FE37680d36F1ED55e38"