#------------------------------------------------------------------------------
# en: Threading Configuration | ru: Конфигурация потоков
#------------------------------------------------------------------------------
# en: Controls parallel execution capacity (min: 1) | ru: Управление количеством параллельных выполнений (минимум: 1)
threads: 10

#------------------------------------------------------------------------------
# en: Timing Settings | ru: Настройки времени
#------------------------------------------------------------------------------
# en: Initial delay range before starting operations (seconds) | ru: Диапазон начальной задержки перед началом выполнения (секунды)
delay_before_start:
    min: 10
    max: 100

# en: Delay between tasks (seconds) | ru: Задержка между задачами (секунды)
delay_between_tasks:
    min: 100
    max: 300


#------------------------------------------------------------------------------
# en: Telegram API hash and ID | ru: Telegram API hash и ID
#------------------------------------------------------------------------------
# https://my.telegram.org/apps 

telegram_api_id: ""
telegram_api_hash: ""

# TELEGRAM DATA
send_stats_to_telegram: true

tg_token: ""  # https://t.me/BotFather
tg_id: ""  # https://t.me/getmyid_bot

#------------------------------------------------------------------------------
# en: MODULES CONFIGURATION  | ru: КОНФИГУРАЦИИ МОДУЛЕЙ
#------------------------------------------------------------------------------
# en: Referral code for standard account registration | ru: Реферальный код для стандартной регистрации аккаунтов
referral_code: ""


#------------------------------------------------------------------------------
# en: Task Execution Configuration | ru: Настройки выполнения задач
#------------------------------------------------------------------------------
# en: Tasks that will always run regardless of their status
# ru: Задачи, которые будут выполняться всегда, независимо от их статуса
always_run_tasks:
  # en: Module names to always run | ru: Имена модулей, задачи которых нужно выполнять всегда
  modules: ["profile", "faucet", "mint_message_nft", "mint_air", "onchain_gm"]

# en: Available module names (copy needed modules to the list above)
# ru: Доступные имена модулей (скопируйте нужные модули в список выше)
available_modules:
  - "profile"           # Профиль
  - "faucet"            # Кран для получения токенов
  - "transfer_stt"      # Перевод STT
  - "mint_ping_pong"    # Минт Ping/Pong
  - "swap_ping_pong"    # Обмен Ping/Pong
  - "mint_usdt"         # Минт USDT
  - "mint_message_nft"  # Минт NFT сообщения
  - "mint_air"          # Минт контракта токена
  - "quest_socials"     # Квест по социальным сетям
  - "quest_sharing"     # Квест по шерингу
  - "quest_darktable"   # Квест по Darktable
  - "quest_playground"  # Квест по Playground 
  - "quest_demons"      # Квест по Demons
  - "quest_gaming_frenzy" # Квест по Gaming Frenzy
  - "onchain_gm"        # Onchain GM
  - "shannon_nft"       # Shannon NFT
  - "yappers_nft"       # Yappers NFT
  - "quest_somnia_gaming_room" # Квест по Somnia Gaming Room
  - "mint_domen"        # Минт домена
  - "nerzo_nft"         # Nerzo NFT
  - "quest_mullet"      # Квест по Mullet
  - "quest_intersection" # Квест по Intersection
  - "quest_masks_of_the_void" # Квест по Masks of the Void

#------------------------------------------------------------------------------
# Network Settings
#------------------------------------------------------------------------------
# Somnia Testnet RPC endpoint
somnia_rpc: https://dream-rpc.somnia.network

# Somnia Testnet Explorer
somnia_explorer: https://shannon-explorer.somnia.network/


#------------------------------------------------------------------------------
# en: Tokens Configuration | ru: Конфигурация токенов
#------------------------------------------------------------------------------
# en: Define tokens and their percentage ranges to be used in operations 
# ru: Определение токенов и их процентных диапазонов для использования в операциях
tokens:
  # en: Token name/symbol | ru: Название/символ токена
  STT:
    # en: Percentage range of token amount to use | ru: Диапазон процентов от суммы токенов для использования
    percent_range:
      min: 5  # 5%
      max: 10 # 10%
    # en: Contract address | ru: Адрес контракта
    contract_address: "0x0000000000000000000000000000000000000000"
  WSTT:
    percent_range:
      min: 5
      max: 10
    # en: Contract address (ERC20) | ru: Адрес контракта (ERC20)
    contract_address: "0x4A3BC48C156384f9564Fd65A53a2f3D534D8f2b7"
  USDT:
    percent_range:
      min: 30
      max: 50
    # en: Contract address (ERC20) | ru: Адрес контракта (ERC20)
    contract_address: "0xE9CC37904875B459Fa5D0FE37680d36F1ED55e38"