#------------------------------------------------------------------------------
# en: Threading Configuration | ru: Конфигурация потоков
#------------------------------------------------------------------------------
# en: Controls parallel execution capacity (min: 1) | ru: Управление количеством параллельных выполнений (минимум: 1)
threads: 1


#------------------------------------------------------------------------------
# Network Settings
#------------------------------------------------------------------------------
# Somnia Testnet RPC endpoint
somnia_rpc: https://dream-rpc.somnia.network

# Somnia Testnet Explorer
somnia_explorer: https://shannon-explorer.somnia.network/


#------------------------------------------------------------------------------
# en: Timing Settings | ru: Настройки времени
#------------------------------------------------------------------------------
# en: Initial delay range before starting operations (seconds) | ru: Диапазон начальной задержки перед началом выполнения (секунды)
delay_before_start:
    min: 0
    max: 0


#------------------------------------------------------------------------------
# en: List of tokens in the network Somnia Devnet | ru: Список токенов в сети Somnia Devnet
#------------------------------------------------------------------------------

tokens: &tokens
  - name: STT
    address: ""
  - name: WSTT
    address: ""
  - name: USDT
    address: ""
  - name: WBTC
    address: ""

#------------------------------------------------------------------------------
# en: Telegram API hash and ID | ru: Telegram API hash и ID
#------------------------------------------------------------------------------

# https://my.telegram.org/apps 

telegram_api_id: ""
telegram_api_hash: ""


#------------------------------------------------------------------------------
# en: MODULES CONFIGURATION  | ru: КОНФИГУРАЦИИ МОДУЛЕЙ
#------------------------------------------------------------------------------


# en: Referral code for standard account registration | ru: Реферальный код для стандартной регистрации аккаунтов
referral_code: ""